### PR TITLE
Integration tests for Event, Attendance, and User

### PR DESCRIPTION
**Pull request by SeanJosephKelly**
- Added integration tests for Event and Attendance, and User
- Fixed bugs regarding event where classes called were not of the correct class (IE Event)
- User now has 100 percent coverage
- integration_users_spec.rb and users_controller now 100% follows rubocop enforced standards

### CODE REVIEW

**Comment by aidanmcgrath** [comment]
Everything looks good!

**Review by SeanJosephKelly — COMMENTED** [review]
Double checked changes, looks good on my end

**Review by James-Garcia1 — APPROVED** [review]
Everything's good, nice tests

**Comment by AnkithP2** [comment]
Tests look good!

**Pull request closed without merging**
